
package proxy;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.3
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "BankConverterWS", targetNamespace = "http://ws/", wsdlLocation = "http://localhost:5200/?wsdl")
public class BankConverterWS
    extends Service
{

    private static final URL BANKCONVERTERWS_WSDL_LOCATION;
    private static final WebServiceException BANKCONVERTERWS_EXCEPTION;
    private static final QName BANKCONVERTERWS_QNAME = new QName("http://ws/", "BankConverterWS");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:5200/?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        BANKCONVERTERWS_WSDL_LOCATION = url;
        BANKCONVERTERWS_EXCEPTION = e;
    }

    public BankConverterWS() {
        super(__getWsdlLocation(), BANKCONVERTERWS_QNAME);
    }

    public BankConverterWS(WebServiceFeature... features) {
        super(__getWsdlLocation(), BANKCONVERTERWS_QNAME, features);
    }

    public BankConverterWS(URL wsdlLocation) {
        super(wsdlLocation, BANKCONVERTERWS_QNAME);
    }

    public BankConverterWS(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, BANKCONVERTERWS_QNAME, features);
    }

    public BankConverterWS(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BankConverterWS(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "BankServicePort")
    public BankService getBankServicePort() {
        return super.getPort(new QName("http://ws/", "BankServicePort"), BankService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BankService
     */
    @WebEndpoint(name = "BankServicePort")
    public BankService getBankServicePort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws/", "BankServicePort"), BankService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (BANKCONVERTERWS_EXCEPTION!= null) {
            throw BANKCONVERTERWS_EXCEPTION;
        }
        return BANKCONVERTERWS_WSDL_LOCATION;
    }

}
